export const CarListData = [
	{
		id: 1,
		name: "Uber Go",
		seat: 4,
		desc: "Affordable compact rides",
		price: 20,
		amount: 35,
		img: "https://d1a3f4spazzrp4.cloudfront.net/car-types/haloProductImages/Hatchback.png",
	},
	{
		id: 2,
		name: "Auto",
		seat: 4,
        desc: "Pay directly to driver, cash/UPI only",
		price: 20,
		amount: 25,
		img: "https://d1a3f4spazzrp4.cloudfront.net/car-types/haloProductImages/v1.1/TukTuk_Green_v1.png",
	},
	{
		id: 3,
		name: "UberXl",
		seat: 6,
        desc: "Comfortable SUVs",
		price: 50,
		amount: 50,
		img: "https://d1a3f4spazzrp4.cloudfront.net/car-types/haloProductImages/package_UberXL_new_2022.png",
	},
    {
		id: 4,
		name: "Go Sedan",
		seat: 4,
        desc: "Affordable compact rides",
		price: 40,
		amount: 40,
		img: "https://d1a3f4spazzrp4.cloudfront.net/car-types/haloProductImages/v1.1/UberX_v1.png",
	},
    {
		id: 5,
		name: "Premier",
		seat: 4,
        desc: "Comfortable sedans,top-quality drivers",
		price: 60,
		amount: 60,
		img: "https://d1a3f4spazzrp4.cloudfront.net/car-types/haloProductImages/package_UberComfort_new_2022.png",
	},
];
